'use client';

import React, { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface MarkdownRendererProps {
  content: string;
  className?: string;
}

/**
 * Recursively parses and converts raw `<br>` or `<br/>` HTML tags embedded
 * inside markdown text nodes (especially inside markdown tables) into actual React <br /> elements.
 */
function renderWithHtmlBreaks(children: React.ReactNode): React.ReactNode {
  if (typeof children === 'string') {
    if (!/<br\s*\/?>/i.test(children)) {
      return children;
    }
    const parts = children.split(/(<br\s*\/?>)/gi);
    return parts.map((part, index) => {
      if (/<br\s*\/?>/i.test(part)) {
        return <br key={index} className="my-1" />;
      }
      return part;
    });
  }

  if (Array.isArray(children)) {
    return React.Children.map(children, (child) => renderWithHtmlBreaks(child));
  }

  if (React.isValidElement(children)) {
    const props = children.props as { children?: React.ReactNode; [key: string]: any };
    if (props && props.children) {
      return React.cloneElement(
        children,
        undefined,
        renderWithHtmlBreaks(props.children)
      );
    }
  }

  return children;
}

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ content, className = '' }) => {
  // Pre-process common HTML tags generated by LLMs to standard markdown or clean spaces
  const sanitizedContent = useMemo(() => {
    if (!content) return '';
    let processed = content;
    // Normalize raw bold/italic tags
    processed = processed.replace(/<b>(.*?)<\/b>/gi, '**$1**');
    processed = processed.replace(/<strong>(.*?)<\/strong>/gi, '**$1**');
    processed = processed.replace(/<i>(.*?)<\/i>/gi, '*$1*');
    processed = processed.replace(/<em>(.*?)<\/em>/gi, '*$1*');
    // Replace non-breaking spaces
    processed = processed.replace(/&nbsp;/gi, ' ');
    return processed;
  }, [content]);

  return (
    <div className={`prose prose-invert max-w-none text-slate-200 text-xs sm:text-sm leading-relaxed ${className}`}>
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          table: ({ node, ...props }) => (
            <div className="my-3 overflow-x-auto rounded-xl border border-slate-800 bg-[#0a0d16] shadow-md">
              <table className="w-full text-left text-xs divide-y divide-slate-800" {...props} />
            </div>
          ),
          thead: ({ node, ...props }) => (
            <thead className="bg-slate-900/90 text-emerald-400 font-bold uppercase tracking-wider text-[11px]" {...props} />
          ),
          th: ({ node, ...props }) => (
            <th className="py-2.5 px-3.5 font-semibold text-slate-200 whitespace-nowrap align-top" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </th>
          ),
          tbody: ({ node, ...props }) => (
            <tbody className="divide-y divide-slate-800/60 font-medium text-slate-300" {...props} />
          ),
          tr: ({ node, ...props }) => (
            <tr className="hover:bg-slate-800/40 transition-colors" {...props} />
          ),
          td: ({ node, ...props }) => (
            <td className="py-2.5 px-3.5 align-top leading-relaxed text-slate-300" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </td>
          ),
          h1: ({ node, ...props }) => (
            <h1 className="text-base font-bold text-white mt-4 mb-2 flex items-center gap-2" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </h1>
          ),
          h2: ({ node, ...props }) => (
            <h2 className="text-sm font-bold text-white mt-3 mb-1.5 flex items-center gap-2" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </h2>
          ),
          h3: ({ node, ...props }) => (
            <h3 className="text-xs font-bold text-emerald-400 mt-2.5 mb-1" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </h3>
          ),
          p: ({ node, ...props }) => (
            <p className="mb-2 last:mb-0 leading-relaxed text-slate-300" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </p>
          ),
          ul: ({ node, ...props }) => (
            <ul className="list-disc list-inside space-y-1 my-2 text-slate-300 pl-1" {...props} />
          ),
          ol: ({ node, ...props }) => (
            <ol className="list-decimal list-inside space-y-1 my-2 text-slate-300 pl-1" {...props} />
          ),
          li: ({ node, ...props }) => (
            <li className="leading-relaxed" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </li>
          ),
          strong: ({ node, ...props }) => (
            <strong className="font-bold text-emerald-300" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </strong>
          ),
          em: ({ node, ...props }) => (
            <em className="text-cyan-300 not-italic font-medium" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </em>
          ),
          code: ({ node, inline, ...props }: any) => (
            inline ? (
              <code className="px-1.5 py-0.5 rounded-md bg-slate-900 border border-slate-800 text-emerald-400 font-mono text-[11px]" {...props} />
            ) : (
              <pre className="p-3 my-2 rounded-xl bg-slate-950 border border-slate-800 overflow-x-auto text-[11px] font-mono text-slate-300">
                <code {...props} />
              </pre>
            )
          ),
          blockquote: ({ node, ...props }) => (
            <blockquote className="border-l-2 border-emerald-500/60 pl-3 my-2 text-slate-400 italic bg-emerald-500/5 py-1 rounded-r-lg" {...props}>
              {renderWithHtmlBreaks(props.children)}
            </blockquote>
          ),
        }}
      >
        {sanitizedContent}
      </ReactMarkdown>
    </div>
  );
};
